name: action_app
version: 1.0.0
description: Github action app that helps to run flutterando_metrics in CI/CD flow.
repository: https://github.com/Flutterando/flutterando-metrics-action
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  actions_toolkit_dart: ^0.5.1
  flutterando_metrics: ^5.7.6
  github: ^9.17.0
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  coverage: ^1.0.3
  lints: ^2.0.0
  mocktail: ^0.3.0
  source_span: ^1.8.1
  test: ^1.21.0
